# Generated by Django 4.1.1 on 2022-09-26 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='student_college', to='student.college'),
        ),
        migrations.AlterField(
            model_name='student',
            name='guide',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='student_teacher', to='student.teacher'),
        ),
    ]
