# Generated by Django 4.1.1 on 2022-09-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_college_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.SlugField(editable=False, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(editable=False, max_length=250, null=True),
        ),
    ]
